# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76410a129a5b543a6987a552fa788c535eb16995ec90c401eae20b1527503d853bf0d53fece3dfe62f914b8f1892071830385af02fe6082f8eed0744b3aee8ee

test:
  secret_key_base: 0a0b891067996ff5e2ea073ec7b0c430096e235ed68884c91d1fd8204b775bc0009092affdbdff739a81173c092c3c071ef6ed92b366ed7fc365a3ed73e660bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
